Add crud products
knowde-academy/team-2-be pull request #10
Opened 2021-08-19 08:19 UTC by mo1502

2021-08-19 08:42 UTC, PatrykTyszka commented on app/controllers/api/v1/products_controller.rb
> +        @product = Product.new(product_params)
fix indetnation

2021-08-19 08:42 UTC, PatrykTyszka commented on app/controllers/api/v1/products_controller.rb
> +              render json: { errors: @product.errors.messages }, status: :unprocessable_entity
never happened coz you don't have validation on destroy.

2021-08-19 08:52 UTC, h4b00 requested changes

2021-08-19 08:52 UTC, h4b00 commented on config/routes.rb
> +      resources :products
only: [:index, :destroy, :show, :update, :create]

2021-08-19 08:52 UTC, h4b00 commented on app/serializers/product_serializer.rb
> +  end
indentation

2021-08-19 08:52 UTC, h4b00 commented on app/models/products_recipes.rb
> +  end
indentation

2021-08-19 08:52 UTC, h4b00 commented on app/models/product.rb
> +  include ActiveModel::Validations
we don't need this

2021-08-19 08:52 UTC, h4b00 commented on db/migrate/20210819070931_add_quantity_to_product.rb
> +    add_column :products, :quantity, :integer
`null: false, default: 1`

2021-08-19 08:52 UTC, h4b00 commented on app/controllers/api/v1/products_controller.rb
> +
fix indentations.

2021-08-19 08:52 UTC, h4b00 commented on app/controllers/api/v1/products_controller.rb
> +
remove empty line at the end

2021-08-23 08:20 UTC, h4b00 approved these changes

2021-08-23 08:21 UTC, merged