Add sign in sign up
knowde-academy/team-2-be pull request #11
Opened 2021-08-19 08:51 UTC by Malgorzataaa

[BE] Add sign_in/sign_up (H)

2021-08-19 08:55 UTC, h4b00 requested changes

2021-08-19 08:55 UTC, h4b00 commented on .vs/ProjectSettings.json
> +}
Add `.vs/*` to git ignore

2021-08-19 08:55 UTC, h4b00 commented on .vs/VSWorkspaceState.json
> +}
same as above

2021-08-19 08:55 UTC, h4b00 commented on Gemfile
> +gem 'devise_token_auth'
you need just one of them, and please add pessimistic version

2021-08-19 08:55 UTC, h4b00 commented on app/controllers/api/v1/recipes_controller.rb
> +      before_action :authenticate_user!
I am not sure if you want to block getting a list of recipes for anonymous users

2021-08-19 08:55 UTC, h4b00 commented on app/controllers/application_controller.rb
> +        include DeviseTokenAuth::Concerns::SetUserByToken
indentation

2021-08-19 08:55 UTC, h4b00 commented on db/migrate/20210819081137_devise_token_auth_create_users.rb
> +
unnecessary empty line

2021-08-19 09:47 UTC, PatrykTyszka commented on Gemfile
> +gem 'devise_token_auth'
version?

2021-08-19 09:47 UTC, PatrykTyszka commented on db/migrate/20210819081137_devise_token_auth_create_users.rb
> +
+1

2021-08-19 09:47 UTC, PatrykTyszka commented on db/migrate/20210819081137_devise_token_auth_create_users.rb
> +      t.string   :unconfirmed_email # Only if using reconfirmable
do you really need this?
look at the model
```
class User < ActiveRecord::Base
  extend Devise::Models
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  include DeviseTokenAuth::Concerns::User
end
```

2021-08-19 11:05 UTC, PatrykTyszka requested changes

2021-08-19 11:05 UTC, PatrykTyszka commented on db/schema.rb
> +    t.string "unconfirmed_email"
you should not have this here...

you need to rollback and run migrations once again if you want to change the schema.

OR you can clear it manually.

2021-08-23 08:21 UTC, h4b00 approved these changes
Just remove these `.vs` files

2021-08-23 08:21 UTC, h4b00 commented on config/initializers/cors.rb
> +    #origins ENV.fetch('API_ALLOWED_ORIGINS').to_s.split(',')
why?

2021-08-23 08:28 UTC, Malgorzataaa commented on config/initializers/cors.rb
> +    #origins ENV.fetch('API_ALLOWED_ORIGINS').to_s.split(',')
I shouldn't send you this file. Without '#' server doesn't work.

2021-08-23 11:00 UTC, closed without merging